### ISSUE TITLE
Encryption key management tools 

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1529]
Parquet Modular Encryption ([PARQUET-1178](https://issues.apache.org/jira/browse/PARQUET-1178)) provides an API that accepts keys, arbitrary key metadata and key retrieval callbacks - which allows to implement basically any key management policy on top of it. This Jira will add tools that implement a set of best practice elements for key management. This is not an end-to-end key management, but rather a set of components that might simplify design and development of an end-to-end solution.

This tool set is one of many possible. There is no goal to create a single or “standard” toolkit for Parquet encryption keys. Parquet has a Crypto Factory interface [(PARQUET-1817](https://issues.apache.org/jira/browse/PARQUET-1817)) that allows to plug in different implementations of encryption key management.

**Reporter**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky
**Assignee**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky
#### Subtasks:
- [X] [[C++] Encryption key management](https://issues.apache.org/jira/browse/PARQUET-1538)
- [X] [Double wrapped key manager](https://issues.apache.org/jira/browse/PARQUET-1612)
- [X] [Key rotation tool](https://issues.apache.org/jira/browse/PARQUET-1613)
- [X] [[C++] Key rotation tool](https://issues.apache.org/jira/browse/PARQUET-1635)
#### Related issues:
- [Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1178) (depends upon)
- [High level interface to Parquet encryption](https://issues.apache.org/jira/browse/PARQUET-1568) (is depended upon by)
- [Properties-Driven Interface to Parquet Encryption](https://issues.apache.org/jira/browse/PARQUET-1854) (is depended upon by)
#### PRs and other links:
- [Design doc](https://docs.google.com/document/d/1bEu903840yb95k9q2X-BlsYKuXoygE4VnMDl9xz_zhk/edit?usp=sharing)

<sub>**Note**: *This issue was originally created as [PARQUET-1373](https://issues.apache.org/jira/browse/PARQUET-1373). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Jason Brugger](https://issues.apache.org/jira/browse/PARQUET-1373?#comment-17149592):
unsubscribe

On Wed, Jul 1, 2020 at 9:31 AM ASF GitHub Bot (Jira) <jira@apache.org>
