### ISSUE TITLE
Parquet bit-packing de/encode optimization

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#1643]
Current Spark use Parquet-mr as parquet reader/writer library, but the built-in bit-packing en/decode is not efficient enough. 

Our optimization for Parquet bit-packing en/decode with jdk.incubator.vector in Open JDK18 brings prominent performance improvement.

Due to Vector API is added to OpenJDK since 16, So this optimization request JDK16 or higher.

**Below are our test results**

Functional test is based on open-source parquet-mr Bit-pack decoding function: **_public final void unpack8Values(final byte[] in, final int inPos, final int[] out, final int outPos)_** __

compared with our implementation with vector API **_public final void unpack8Values_vec(final byte[] in, final int inPos, final int[] out, final int outPos)_**

We tested 10 pairs (open source parquet bit unpacking vs ours optimized vectorized SIMD implementation) decode function with bit width=\{1,2,3,4,5,6,7,8,9,10}, below are test results:

<img src="image-2022-06-15-22-56-08-396.png" width="437" height="223" />

We integrated our bit-packing decode implementation into parquet-mr, tested the parquet batch reader ability from Spark VectorizedParquetRecordReader which get parquet column data by the batch way. We construct parquet file with different row count and column count, the column data type is Int32, the maximum int value is 127 which satisfies bit pack encode with bit width=7,   the count of the row is from 10k to 100 million and the count of the column is from 1 to 4.

<img src="image-2022-06-15-22-57-15-964.png" width="453" height="229" />

<img src="image-2022-06-15-22-58-01-442.png" width="439" height="217" />

<img src="image-2022-06-15-22-58-40-704.png" width="415" height="208" />

**Reporter**: [Fang-Xie](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Fang-Xie) / @Fang-Xie
**Assignee**: [Fang-Xie](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=Fang-Xie) / @Fang-Xie
#### Subtasks:
- [X] [Parquet java vector decode optimization for Big Endian](https://issues.apache.org/jira/browse/PARQUET-2234)
- [X] [Parquet java vector decode optimization Long for Big Endian](https://issues.apache.org/jira/browse/PARQUET-2235)
- [X] [Parquet java vector decode optimization Long for Little Endian](https://issues.apache.org/jira/browse/PARQUET-2236)
#### Related issues:
- [Extend vectorized bit unpacking benchmark for various bit sizes.](https://issues.apache.org/jira/browse/PARQUET-2375) (is a parent of)
#### Original Issue Attachments:
- [image-2022-06-15-22-56-08-396.png](https://issues.apache.org/jira/secure/attachment/13045135/image-2022-06-15-22-56-08-396.png)
- [image-2022-06-15-22-57-15-964.png](https://issues.apache.org/jira/secure/attachment/13045136/image-2022-06-15-22-57-15-964.png)
- [image-2022-06-15-22-58-01-442.png](https://issues.apache.org/jira/secure/attachment/13045137/image-2022-06-15-22-58-01-442.png)
- [image-2022-06-15-22-58-40-704.png](https://issues.apache.org/jira/secure/attachment/13045138/image-2022-06-15-22-58-40-704.png)

<sub>**Note**: *This issue was originally created as [PARQUET-2159](https://issues.apache.org/jira/browse/PARQUET-2159). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2159?#comment-17554652) / @theosib-amazon:
Could you add a link to the PR, please?

**Comment by asfimport** [comment]
[Fang-Xie](https://issues.apache.org/jira/browse/PARQUET-2159?#comment-17555081) / @Fang-Xie:
Thanks @theosib-amazon, these improvements depend on Vector API in JDK 16 or higher version, how do we consider about JDK version issue?

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2159?#comment-17555099) / @theosib-amazon:
I frequently wish Java had a preprocessor like C++ that would solve your problem. Currently, we have to build ParquetMR with Java 8, and plenty of things that depend on it (like Trino and Presto) use Java 11 at the latest. There are some solutions involving runtime loading of class files (e.g. <https://stackoverflow.com/questions/4526113/java-conditional-compilation-how-to-prevent-code-chunks-from-being-compiled),> but there's already enough weirdness in the ParquetMR build process (e.g. compile-time generated code that makes debugging a huge pain) that I hesitate to suggest making it even more challenging.

Where actually is the code coming from that you're working on? Is it part of ParquetMR or some other library? I seem to recall that when debugging Trino, the code you're working on has to go through the decompiler in IntelliJ. So if it's already external in some way, then it probably wouldn't hurt to make it just a bit more dynamic, where ParquetMR loads different versions of the bit-packing library depending on the Java version.

**Comment by asfimport** [comment]
[Fang-Xie](https://issues.apache.org/jira/browse/PARQUET-2159?#comment-17555116) / @Fang-Xie:
We implemented Parquet bit packing en/decode using JDK Vector API which can get benefits from SIMD instruction, refer to <https://openjdk.org/jeps/417>

 The original bit-packing code is generated from <https://github.com/apache/parquet-mr/blob/master/parquet-generator/src/main/java/org/apache/parquet/encoding/bitpacking/ByteBasedBitPackingGenerator.java>

via maven build. We reimplemented bit-pack functions

but it had to compile and run under JDK 16 or higher (needs Vector APIs), So not sure we can contribute code to Parquet community.

**Comment by asfimport** [comment]
[Timothy Miller](https://issues.apache.org/jira/browse/PARQUET-2159?#comment-17555142) / @theosib-amazon:
If this is already being generated at runtime, then it sounds to me like you might be able to generate different things depending on the compiler's source version setting.

**Comment by asfimport** [comment]
[jiangjiguang0719](https://issues.apache.org/jira/browse/PARQUET-2159?#comment-17622924) / @jiangjiguang:
@theosib-amazon  As you mentioned above "compile-time generated code that makes debugging a huge pain".   And current different computing engines support different java versions (e.g.  presto supports java8,  trino supports java17,  spark supports java17 and flink supports java11), so I have two option suggestion:
1、Upgrade parquet-mr to java17(java 17 is lts), and generate different things depending on the compiler's java source version setting.
2、Create a new Java project as library to support java17 parquet bit-packing de/encode opt.  without  generating code.
