### ISSUE TITLE
Parquet modular encryption

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2110]
A mechanism for modular encryption and decryption of Parquet files. Allows to keep data fully encrypted in the storage - while enabling efficient analytics on the data, via reader-side extraction / authentication / decryption of data subsets required by columnar projection and predicate push-down.

Enables fine-grained access control to column data by encrypting different columns with different keys.

Supports a number of encryption algorithms, to account for different security and performance requirements.

**Reporter**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky
**Assignee**: [Gidon Gershinsky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gershinsky) / @ggershinsky
#### Subtasks:
- [X] [Thrift crypto metadata structures](https://issues.apache.org/jira/browse/PARQUET-1227)
- [X] [parquet-format-structures encryption](https://issues.apache.org/jira/browse/PARQUET-1228)
- [X] [parquet-mr code changes for encryption support](https://issues.apache.org/jira/browse/PARQUET-1229)
- [X] [Document the modular encryption in parquet-format](https://issues.apache.org/jira/browse/PARQUET-1232)
- [X] [Crypto package in parquet-mr](https://issues.apache.org/jira/browse/PARQUET-1286)
- [X] [Separate iv_prefix for GCM and CTR modes](https://issues.apache.org/jira/browse/PARQUET-1398)
- [X] [RowGroup offset and total compressed size fields](https://issues.apache.org/jira/browse/PARQUET-1401)
- [X] [Enable old readers to access unencrypted columns in files with plaintext footer](https://issues.apache.org/jira/browse/PARQUET-1419)
- [X] [Detailed crypto specification](https://issues.apache.org/jira/browse/PARQUET-1450)
- [X] [Thrift crypto updates](https://issues.apache.org/jira/browse/PARQUET-1477)
- [X] [Update encryption spec for Bloom filter encryption](https://issues.apache.org/jira/browse/PARQUET-1618)
- [X] [Merge crypto spec and structures to format master](https://issues.apache.org/jira/browse/PARQUET-1619)
- [X] [Encryption: Interop and Function test suite for Java version](https://issues.apache.org/jira/browse/PARQUET-1807)
- [X] [Merge encryption branch into master](https://issues.apache.org/jira/browse/PARQUET-1884)
#### Related issues:
- [Passing Field Metadata to Parquet](https://issues.apache.org/jira/browse/SPARK-25858) (Blocked)
- [Upgrade Parquet to 1.12.0](https://issues.apache.org/jira/browse/HIVE-25119) (relates to)
- [[C++] Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1300) (depends upon)
- [CLONE - [C++] Parquet modular encryption](https://issues.apache.org/jira/browse/PARQUET-1906) (depends upon)
- [Data obfuscation layer for encryption](https://issues.apache.org/jira/browse/PARQUET-1376) (is depended upon by)
- [[C++] Data set integrity tool](https://issues.apache.org/jira/browse/PARQUET-1457) (is depended upon by)
- [Encryption key management tools ](https://issues.apache.org/jira/browse/PARQUET-1373) (is depended upon by)
- [High level interface to Parquet encryption](https://issues.apache.org/jira/browse/PARQUET-1568) (is depended upon by)
- [Sample of usage Parquet-1396 and Parquet-1178 for column level encryption with pluggable key access](https://issues.apache.org/jira/browse/PARQUET-1397) (is depended upon by)
#### PRs and other links:
- [Parquet modular encryption design doc](https://docs.google.com/document/d/1T89G7xR0zHFV1f2pjTO28jtfVm8qoNVGEJQ70Rsk-bY/edit?usp=sharing)
- [Performance estimation](https://docs.google.com/document/d/1WasYsgYFXJPkZUWtERF_NiqNMJECor1eo_kFi3Og_Qg/edit?usp=sharing)

<sub>**Note**: *This issue was originally created as [PARQUET-1178](https://issues.apache.org/jira/browse/PARQUET-1178). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Mohammad Islam](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16357730):
Very good and relevant Jira @ggershinsky.

We ( at Uber ) are also interested about this feature.  How it is coming along?

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16358011) / @ggershinsky:
Thank you Mohammad, this is moving along nicely.

The design is converging (thanks to Julien's and Marcel's feedback, and Ryan's spot-on comments), the implementation is half-way there, testing will start soon. A pull request should be ready in a couple of weeks.

**Comment by asfimport** [comment]
[Mohammad Islam](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16366121):
Thanks @ggershinsky for the updates.

I will also review the doc and add some of our requirements into the doc, if anything missing.

Looking forward for  the patch.

**Comment by asfimport** [comment]
[Cesar Delgado](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16652157) / @beettlle:
Saw the modular encryption doc were merged a couple days ago.  Very happy to see this Jira moving along.  Can't wait to have something to try in the near future.

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16653583) / @ggershinsky:
Thanks Cesar, sounds good!

**Comment by asfimport** [comment]
[DB Tsai](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16654176):
This feature will be very important for both Spark community and our use-case. We're looking forward to it! Thanks.

**Comment by asfimport** [comment]
[Gang Ma](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16854454):
Notice that the encryption format has been merged to the encryption branch of parquet-format repo, and some implementation pr has been filed to parquet-mr repo, so is there any release plan for this feature? will it be available in parquet 1.12.0 ?

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-16958871) / @gszadovszky:
@ggershinsky, this is an umbrella jira. Is it related to the parquet-format release 2.7.0? Please, remove the tag if not.

**Comment by asfimport** [comment]
[Jason Brugger](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17034916):
What's the best way to get started with this on a Databricks cluster? If I install _format-2.7.0_ as a new library, how would I reference this data source in lieu of the cluster's default parquet library?

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17035421) / @ggershinsky:
`[~jasbru]`  Currently, this can't be run on a Databricks cluster - besides the Thrift structures in parquet-format-2.7.0, it  will also require a Java implementation of parquet encryption and key management libraries (not merged yet, but we're working on this).

**Comment by asfimport** [comment]
[Bogdan](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17060539):
I tried out the encryption branch but the latest commit (#614) is not even compiling.

Would you recommend a commit I could checkout and test the encryption feature?

Thanks in advance!

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17060707) / @ggershinsky:
`[~Vatkov]`, a number of pull requests are under construction.

Hopefully they will be sent to the repository by the next week. No guarantees they'll be merged by that time, but still you'll be able to assemble the outstanding pr's, and build/run the encryption code.

**Comment by asfimport** [comment]
[Bogdan](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17060786):
Thanks @ggershinsky!

**Comment by asfimport** [comment]
[Venkata Satya Pradeep Srikakolapu](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17098253):
This feature nicely fits in my case. Any timeline on this? I am basically looking for a format which an encrypt PII/PHI columns when storing on Data Lake Store in Azure DataBricks cluster. Do you recommend any other alternative if this feature is not going to be available soon?

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17098355) / @ggershinsky:
[~prdpsvs@gmail.com] this feature is already implemented in parquet-cpp code (check Apache Arrow, from version 0.16).
If you need a Java version, it should be available soon in parquet-mr, check #[776 ](https://github.com/apache/parquet-mr/pull/776)- the last pull request in the basic encryption layer. We're working to make it a part of the next parquet-mr release, 1.12. No specific timelines at this point.
On top of the basic encryption layer, we're building a high level interface that will simplify using the parquet encryption, see [PARQUET-1568](https://issues.apache.org/jira/browse/PARQUET-1568). Updated details are coming up, we plan to try to make it a part of v1.12 too.

**Comment by asfimport** [comment]
[Venkata Satya Pradeep Srikakolapu](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17098529):
Thank you @ggershinsky  for quick reply. Could you please point me to an example for implementing this feature in Apache arrow? I am interested to understand key management for encrypting/decrypting columns with Apache Arrow. 

I am working with a customer from Health Care space. My customer wants to encrypt sensitive columns while persisting data to the disk (Data Lake). I see few options for column encryption & Key Management
1. Apache Arrow with Python - Do you recommend to use Apache Arrow with Scala?
1. Parquet - MR - Not released yet 
1. Encryption With ORC files (similar to Parquet Modular encryption) - <https://jira.apache.org/jira/browse/ORC-14?jql=text%20~%20%22column%20level%20encryption%20to%20ORC%20files%22>
   
**Some context**: My customer is using Apache Parquet with scala + Spark extensively. My customer is also planning to use Python with Parquet. 

Could you please recommend what would be the best choice?

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17098549) / @ggershinsky:
hard to say what's best at this point. Here's the arrow/parquet-cpp encryption [sample](https://github.com/apache/arrow/blob/apache-arrow-0.16.0/cpp/examples/parquet/low-level-api/encryption-reader-writer-all-crypto-options.cc).

**Comment by asfimport** [comment]
[Bogdan](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17201529):
@ggershinsky, any ideas how the schedule for 1.12 looks like? Any chance for it to happen before 2021?

**Comment by asfimport** [comment]
[Mike Dias](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17203163):
Hello, we'd love to see this feature released so we to start the work required to fully integrate with Spark. Right now we are compiling both Parquet and Spark master branches to get access to the feature and that is preventing us to move forward with column encryption in production systems. Is there any expected date to release it in 1.12?

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17203178) / @gszadovszky:
[~mike_dias], the Spark community is still working on to migrate to 1.11 (see SPARK-26346 for details). There are transitive dependency issues with Avro. I cannot say any ETA for 1.12 but I am not sure if even we would be able to release it tomorrow it would be available in Spark soon.

**Comment by asfimport** [comment]
[Henry Jones](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17203194):
Similar to the questions above, **I'd love a rough estimate for the target release date for this**. Storing sensitive data in encrypted form whilst retaining the ability to filter and search is an amazing feature which we'd love to work with at our company.

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17203214) / @gszadovszky:
I hope, we can do a release candidate next month.

**Comment by asfimport** [comment]
[Gidon Gershinsky](https://issues.apache.org/jira/browse/PARQUET-1178?#comment-17309267) / @ggershinsky:
Released. Thanks to all who've contributed to this new Parquet capability!
