### ISSUE TITLE
Column indexes

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2123]
Write the column indexes described in PARQUET-922.
 This is the first phase of implementing the whole feature. The implementation is done in the following steps:
- Utility to read/write indexes in parquet-format
- Writing indexes in the parquet file
- Extend parquet-tools and parquet-cli to show the indexes
- Limit index size based on parquet properties
- Trim min/max values where possible based on parquet properties
- Filtering based on column indexes
  
  The work is done on the feature branch `column-indexes`. This JIRA will be resolved after the branch has been merged to `master`.

**Reporter**: [Gabor Szadovszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gszadovszky) / @gszadovszky
**Assignee**: [Gabor Szadovszky](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=gszadovszky) / @gszadovszky
#### Subtasks:
- [X] [Column indexes: read/write API](https://issues.apache.org/jira/browse/PARQUET-1211)
- [X] [Column indexes: Show indexes in tools](https://issues.apache.org/jira/browse/PARQUET-1212)
- [X] [Column indexes: Limit index size](https://issues.apache.org/jira/browse/PARQUET-1213)
- [X] [Column indexes: Truncate min/max values](https://issues.apache.org/jira/browse/PARQUET-1214)
- [X] [Column indexes: Filtering](https://issues.apache.org/jira/browse/PARQUET-1310)
- [X] [Column Indexes: Invalid row indexes for pages starting with nulls](https://issues.apache.org/jira/browse/PARQUET-1364)
- [X] [Incorrect check for ASCENDING/DESCENDING at column index write path](https://issues.apache.org/jira/browse/PARQUET-1379)
- [X] [Fix issues of NaN and +-0.0 in case of float/double column indexes](https://issues.apache.org/jira/browse/PARQUET-1386)
- [X] [Improve value skipping at page synchronization](https://issues.apache.org/jira/browse/PARQUET-1389)
- [X] [appendRowGroup will loose pageIndex](https://issues.apache.org/jira/browse/PARQUET-2340)
#### Related issues:
- [Don't write page level statistics](https://issues.apache.org/jira/browse/PARQUET-1365) (blocks)
- [Write index page in parquet file](https://issues.apache.org/jira/browse/PARQUET-1207) (is duplicated by)
- [Limit page size based on maximum row count](https://issues.apache.org/jira/browse/PARQUET-1414) (relates to)
- [Make Spark SQL support Column indexes](https://issues.apache.org/jira/browse/PARQUET-1739) (relates to)
- [Add index pages to the format to support efficient page skipping](https://issues.apache.org/jira/browse/PARQUET-922) (depends upon)
- [Improve logic when to write column indexes](https://issues.apache.org/jira/browse/PARQUET-1415) (is depended upon by)
- [Benchmark filtering column-indexes](https://issues.apache.org/jira/browse/PARQUET-1435) (is depended upon by)
#### PRs and other links:
- [GitHub Pull Request #527](https://github.com/apache/parquet-mr/pull/527)
- [format PR](https://github.com/apache/parquet-format/pull/81)

<sub>**Note**: *This issue was originally created as [PARQUET-1201](https://issues.apache.org/jira/browse/PARQUET-1201). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1201?#comment-16348720) / @gszadovszky:
@rdblue, I've added a pull request for parquet-format which is required for the changes to be done in parquet-mr. I guess, we also shall create a parquet-format release with this change so we can rely on these changes in parquet-mr. Could you please help in this?

**Comment by asfimport** [comment]
[Pankaj Sharma](https://issues.apache.org/jira/browse/PARQUET-1201?#comment-16591524):
Thanks for all the work on this 1201.  Cant wait for it to get completed so we can utilize secondary indexes in Parquet

**Comment by asfimport** [comment]
[Gabor Szadovszky](https://issues.apache.org/jira/browse/PARQUET-1201?#comment-16593386) / @gszadovszky:
Thanks, `[~pshar0]`. I'm waiting for some reviews for the last task. If it is ready I'll push it to the feature branch and start working on merging the whole branch to master.

Hopefully, will be done soon.

**Comment by asfimport** [comment]
[Ryan Blue](https://issues.apache.org/jira/browse/PARQUET-1201?#comment-16631130) / @rdblue:
@gszadovszky, where is the branch for page skipping? Is it this one? https://github.com/apache/parquet-mr/tree/column-indexes

I just went to review it, but I don't see a PR. Could you open one against master?

**Comment by asfimport** [comment]
[Zoltan Ivanfi](https://issues.apache.org/jira/browse/PARQUET-1201?#comment-16631463) / @zivanfi:
@rdblue That is the branch indeed. Our idea with the feature branch was that each commit to the feature branch will happen via a PR and will go through the regular thorough reviewing process. We wanted to avoid opening a giant PR at the end which would be very hard to review anyway due to its sheer size. The community accepted this approach on the Parquet sync where we discussed it. Could you please review the individual PR-s instead? Thanks!
