### ISSUE TITLE
Unified Rewriter Tool  

### ISSUE THREAD

**Issue by asfimport** [apache/parquet-java#2637]
During the discussion of PARQUET-2071, we came up with the idea of a universal tool to translate the existing file to a different state while skipping some level steps like encoding/decoding, to gain speed. For example, only decompress pages and then compress directly. For PARQUET-2071, we only decrypt and then encrypt directly. This will be useful for the existing data to onboard Parquet features like column encryption, zstd etc. 

We already have tools like trans-compression, column pruning etc. We will consolidate all these tools with this universal tool. 

**Reporter**: [Xinli Shang](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=shangx@uber.com) / @shangxinli
**Assignee**: [Gang Wu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=wgtmac) / @wgtmac
#### Subtasks:
- [X] [Refactor different file rewriters to use single implementation](https://issues.apache.org/jira/browse/PARQUET-2227)
- [X] [ParquetRewriter supports more than one input file](https://issues.apache.org/jira/browse/PARQUET-2228)
- [X] [ParquetRewriter supports masking and encrypting the same column](https://issues.apache.org/jira/browse/PARQUET-2229)
- [X] [Add a new rewrite command powered by ParquetRewriter](https://issues.apache.org/jira/browse/PARQUET-2230)
- [X] [ParquetRewriter supports merging files by record](https://issues.apache.org/jira/browse/PARQUET-2248)
#### Externally tracked issue: [https://docs.google.com/document/d/1Ryt5uXnp-YwOrsnIDrGdTMoFfbOaTM6X39pBLHOa_50](https://docs.google.com/document/d/1Ryt5uXnp-YwOrsnIDrGdTMoFfbOaTM6X39pBLHOa_50)

<sub>**Note**: *This issue was originally created as [PARQUET-2075](https://issues.apache.org/jira/browse/PARQUET-2075). Please see the [migration documentation](https://issues.apache.org/jira/browse/PARQUET-2502) for further details.*</sub>

**Comment by asfimport** [comment]
[Gang Wu](https://issues.apache.org/jira/browse/PARQUET-2075?#comment-17645349) / @wgtmac:
As discussed offline, I will work on it. So I just changed the assignee to me. [~shangx@uber.com]
